# For most projects, this workflow file will not need changing; you simply need
# to commit it to your repository.
#
# You may wish to alter this file to override the set of languages analyzed,
# or to provide custom queries or build logic.
name: "CodeQL"

on:
  push:
    branches: [master]

jobs:
  check-quality:
    runs-on: ubuntu-latest
    name: A job to check the code quality
    steps:
    - name: check code meets quaity standerds 
      id: code-inspector
      uses: actions/checkout@v3
      with:
        min_quality_grade: 'GOOD'
	      min_quality_score: '80'
		    max_defects_rate: '0.0001'
		    max_complex_functions_rate: '0.0001'
		    max_long_functions_rate: '0.0001'
		    project_name: 'sprint-crowd-UI-framework'
		    max_timeout_sec: '600'
